import json, re, unittest, hashlib
from pathlib import Path
from html.parser import HTMLParser
from urllib.parse import urlsplit,unquote
ROOT=Path(__file__).resolve().parents[1]
class Links(HTMLParser):
    def __init__(self):super().__init__();self.links=[]
    def handle_starttag(self,tag,attrs):
        for k,v in attrs:
            if k in ('href','src') and v:self.links.append(v)
class Foundation(unittest.TestCase):
    def test_counts_and_descriptions(self):
        tree=json.loads((ROOT/'2-data.json').read_text());leaves=[]
        def walk(n):
            if n.get('url'):leaves.append(n)
            for c in n.get('children',[]):walk(c)
        walk(tree)
        self.assertEqual(len(tree['children']),33)
        self.assertEqual(len(leaves),1168)
        self.assertTrue(all(n.get('arDescription') for n in leaves))
    def test_no_invented_review_dates(self):
        reviews=json.loads((ROOT/'3-review-queue.json').read_text())
        self.assertEqual(len(reviews),1109)
        self.assertTrue(all(r['last_checked'] is None and r['review_status']=='pending' for r in reviews))
    def test_admin_preserved(self):
        self.assertEqual((ROOT/'site/admin.html').read_bytes(),(ROOT/'_site/admin.html').read_bytes())
    def test_required_pages(self):
        for f in ['index.html','admin.html','commands.html','methodology.html','verification.html','newsrag.html','rag.html','smart-search.html','catalog/category-01.html']:
            self.assertTrue((ROOT/'_site'/f).is_file(),f)
    def test_local_links(self):
        missing=[]
        for p in (ROOT/'_site').rglob('*.html'):
            parser=Links();parser.feed(p.read_text())
            for link in parser.links:
                u=urlsplit(link)
                if u.scheme or u.netloc or not u.path or u.path.startswith('data:'):continue
                if 'pagefind/' in u.path:continue # generated by pinned Pagefind after source build
                target=(p.parent/unquote(u.path)).resolve()
                if not target.exists():missing.append((str(p.relative_to(ROOT/'_site')),link))
        self.assertEqual(missing,[])
    def test_no_placeholders(self):
        self.assertNotIn('__DATA_JSON__',(ROOT/'_site/index.html').read_text())
    def test_font_and_credit(self):
        text=(ROOT/'_site/index.html').read_text()
        self.assertIn('صممت بواسطة مهندس شحاته السيد',text)
        self.assertIn('Cairo',text)
    def test_deploy_no_zip(self):
        text=(ROOT/'.github/workflows/deploy.yml').read_text()
        self.assertNotIn('unzip',text)
        self.assertIn('npm ci',text)
if __name__=='__main__':unittest.main()
